### ISSUE TITLE
The output widget resizes when text is changed in the window's footer

### ISSUE THREAD

**Issue by Goldensunboy** [wario-land/WL4Editor#207]
The output dock widget will automatically resize itself to the default size if the text at the bottom of the main window is modified.

This will not happen if you undock and redock the widget.

**Comment by shinespeciall** [comment]
this issue seems disappeared after i discarding the phantom style theme and port the WL4Editor to Qt6. so just let me close the issue for now. if someone show us that the output dock widget become annoying again at some time. then we could create a new issue.
