### ISSUE TITLE
Corruption when adding new room

### ISSUE THREAD

**Issue by Goldensunboy** [wario-land/WL4Editor#241]
beco: seems like adding new room corrupts the rom if it's already edited before. i tried to add a room in my hack but it made the rom unopenable with the editor, also got the same result with your hack (HW).

**Comment by becored** [comment]
Repro:
- Open a ROM (which is not vanilla but already edited before, such as Wario Land 4: Parallel World and Hollow Wario)
- Edit > Add > New Room
- Save

**Comment by Goldensunboy** [comment]
![image](https://user-images.githubusercontent.com/2107532/88989719-1dc8a100-d291-11ea-958e-8a6a98f16010.png)

**Comment by Goldensunboy** [comment]
- Open editor
- Open vanilla ROM
- Add 1 tile anywhere in the room
- Save as > "file.gba"
- Close editor
- Open editor
- Open "file.gba"
- Edit > Add > New Room
- Save
- Close editor
- Open editor
- Open "file.gba"
the crash only occurs if one of the rooms in HoH is already modified, before you try to add a new room. It does not occur if you do it in the same editor session

**Comment by Goldensunboy** [comment]
RCA (ssp):
so when creating new room, i set all the layers in the new room dirty, it will disable the old save chunk when saving the new rooms layer data, so if the pointer of layer data point to some save chunk used also by the room 0, then that chunk is going to be disabled
so the third time when opening the rom, there will be problems on loading the data
i mean that save chunk is disabled and then used to save some other data in the new room, then the room 0 layer 1 pointer still point to it, but indeed the data changed
