### ISSUE TITLE
Re-saving with the Patch Manager causes "P" hooks to continually get longer

### ISSUE THREAD

**Issue by Spleeeeen** [wario-land/WL4Editor#256]
- Open a ROM
- Open the Patch Manager
- Press the "Add" button
- Press Browse and select a C patch file* which includes the "P" signifier in the Hook
- Press OK, then Save
- Open the Patch Manager again. The Hook is now (correctly) 4 bytes longer. If you press Edit, you can see that it comes after the "P".
- Save the Patch Manager, then Open it again. Notice that the Hook is 4 bytes longer.
- Repeat the previous step any number of times; the Hook will continue to grow.

*Here is an example of a file which will generate the problem: https://hatebin.com/cbbiomfryi

**Comment by Goldensunboy** [comment]
Reproduced. The hook string shown in the manager is actually not supposed to display the address from the P identifier.
