### ISSUE TITLE
Can't drag over the tiles in the main graphic view when Rectangle Select Mode is active

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#287]
As the title says, only can select one tile in the main graphic view even when Rectangle Select Mode is active.

**Comment by shinespeciall** [comment]
caused by some bad code tweaking:
https://media.discordapp.net/attachments/446336634015842314/758550429951852544/unknown.png
fixed:
https://cdn.discordapp.com/attachments/674854161812029450/758677018907901962/unknown.png

**Comment by Goldensunboy** [comment]
Not high pri because no corruption

**Comment by shinespeciall** [comment]
okay.
