### ISSUE TITLE
Adding a room in Ruby Passage Level 2 will corrupt the rom file

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#290]
Repro:
- Open a vanilla ROM
- Load Level: Ruby Passage - Second Level
- Edit > Add > New Room
- Save ROM
- Close the rom
- Reopen the rom
- Load Level: Ruby Passage - Second Level
- The editor crashes

**Comment by shinespeciall** [comment]
caused by wrong layer pointer reset in RoomHeader when creating new room
https://cdn.discordapp.com/attachments/472378488125521921/764501214473486416/unknown.png
