### ISSUE TITLE
cannot find memcpy.o file when execute linker script when the folder path have space in the whole string, then the whole patch feature cannot work

### ISSUE THREAD

**Issue by shinespeciall** [wario-land/WL4Editor#297]
this is an existing issue on the main branch, delete this issue when using new code (that part of logic will be deprecated perhaps, idk, ask @Goldensunboy for detalis)

**Comment by Goldensunboy** [comment]
Closing this issue as it is no longer relevant. With #305, the memcpy.o object file is no longer needed.
