### ISSUE TITLE
Making changes on Spriteset Load Table will corrupt the edited rom file

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#303]
Repro:
- Open the edited ROM ([Wario Land 4: Parallel World v0.41](https://drive.google.com/file/d/1yhEex8tPwjOvvarGu52CCwt054ZeitNu/view?usp=sharing))
- Edit > Edit Entities and EntitySets
- Load Spriteset ID: 1
Set Spriteset Load Table: 7b 00 80 01 
- Reset then OK
- Save ROM
- Close and reopen the rom
- The editor crashes

**Comment by shinespeciall** [comment]
data corruption happens and the editor crash when decompressing layer 0 in Room 0 in the first level
![image](https://user-images.githubusercontent.com/28697038/101172009-8b3f7080-367b-11eb-90ab-47ff9cc49696.png)

**Comment by shinespeciall** [comment]
The problem is caused by a wrong size match in ChunkAllocator lambda function when saving file in SaveFile function. The required chunk size should always plus 12 for the RATS header length, which is missing in the new save engine.

**Comment by shinespeciall** [comment]
seems this should be the fix there, the original logic looks incorrect in the operators
![image](https://user-images.githubusercontent.com/28697038/101183388-6acae280-368a-11eb-82d7-f7429e9f355b.png)
