### ISSUE TITLE
Making hook string longer in applied C patch will corrupt the rom file

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#313]
- Open a vanilla ROM
- Open patch manager
- Add a C patch
- Save patches to ROM
- Make the hook string longer in added C patch
- Open patch manager
- Reselect the C patch (to apply the hook string)
- Save patches to ROM
Internal error while saving changes to ROM: Invalidation chunk references an invalid RATS identifier for existing chunk. Address: 0x78FA18. Changes not saved.

**Comment by Goldensunboy** [comment]
- Open vanilla ROM
- Open patch manager
- Add C patch: [FrameOperation.zip](https://github.com/wario-land/WL4Editor/files/5741255/FrameOperation.zip)
- Save patches to ROM
- **Save the unmodified level with ctrl+S**
- Open the C file in a text editor, and append to the hook string: `00` then save the file
- Open patch manager
- Select the patch which was already added, and then the edit button
- In the patch edit dialog, browse for the C file again
- Press ok to close out the patch edit dialog, then save patches to ROM
- Save the unmodified level with ctrl+S
video: https://www.youtube.com/watch?v=cldKSQL7oU4

**Comment by Goldensunboy** [comment]
This specific repro causes the following corruption of an existing camera boundary chunk:
![image](https://user-images.githubusercontent.com/2107532/103338944-e96e3200-4a34-11eb-9c63-d0836f02214d.png)
