### ISSUE TITLE
Can't import palette in Tileset Editor

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#318]
Repro:
- Open a vanilla rom
- Edit > Edit Current Tileset
- Export Palette
- Save as "test.pal"
- Import Palette
- Select "test.pal"
- Error: Wrong file format!

**Comment by shinespeciall** [comment]
![image](https://user-images.githubusercontent.com/28697038/103449325-8c4ad880-4ce1-11eb-9eef-17d1b6c86d15.png)
repro successfully.
