### ISSUE TITLE
Binary patches cannot be removed after once saved patches in Patch Manager

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#337]
Repro:
- Open a vanilla rom
- Open Patch Manager
- Add a Binary type patch (Hook address: 0x0, Hook: FF)
- Save patch
- Close the editor
- Reopen the rom
- Open Patch Manager
- Save patch (no change)
- Open Patch Manager
- Remove the Binary type patch
- Save patch
- Open the rom with Hex editor and check 0x00 value remaining "FF" (original value is "2E")

**Comment by shinespeciall** [comment]
this problem is caused by some bad logic in the patch saving function, the old code always copy the substituded bytes from the hook address every time when doing save, without checking if the patch is a hook-only patch or not.
