### ISSUE TITLE
Hook string of binary patch disappears by save and edit in Patch Manager

### ISSUE THREAD

**Issue by becored** [wario-land/WL4Editor#341]
Repro:
- Open a vanilla rom
- Open Patch Manager
- Add a Binary type patch (Hook address: 0x0, Hook: FF)
- Save patch
- Open Patch Manager
- Edit added patch  (Hook address: 0x0, Hook: 00)
- Save patch
- Open Patch Manager
- Hook string of the patch disappears

**Comment by shinespeciall** [comment]
still caused by bad logic in PatchUtils::SavePatchesToROM(...)
there is some weird code in other place need some fix too

**Comment by becored** [comment]
Overlaps error occurs when try to edit the hook string of the patch in hook address at not 0x0.

Repro:
- Open a vanilla rom
- Open Patch Manager
- Add a Binary type patch (Hook address: **0x39610**, Hook: FF)
- Save patch
- Open Patch Manager
- Edit added patch (Hook address: **0x39610**, Hook: 00)
- This patch's hook (0x39610 - 0x39610) overlaps with the hook of another patch (0x39610 - 0x39610)
