### ISSUE TITLE
Rectangle select mode can disable switching rooms even after disabling rectangle select.

### ISSUE THREAD

**Issue by Kleyment** [wario-land/WL4Editor#359]
Bug originally found by IsaGoodFriend 

Bug:  Rectangle select mode can disable switching rooms even after disabling rectangle select.
Steps:  Enable rectangle select mode, and select anything.  Disable select mode.  You won't be able to change rooms at all

Probably caused by

`singleton->SetChangeCurrentRoomEnabled(false);` in MainGraphicsView.cpp line 68

Is this necessary to prevent a bug ? Or can we remove it safely ?

**Comment by shinespeciall** [comment]
three cases:

switch on rect select mode
rect-select some tiles
do nothing else then switch off rect select mode
result: cannot change rooms

switch on rect select mode
rect-select some tiles
do a drag and drop and don't click other non-selected tiles to finish the copy operation then switch off rect select mode
result: cannot change rooms

switch on rect select mode
rect-select some tiles
finish the whole copy operation then switch off rect select mode
result: the 2 room switch buttons work again

**Comment by shinespeciall** [comment]
since i didn't support copy tiles and paste to a different room, the room switch buttons (also the script APIs) should be disabled during the rect select mode

**Comment by Kleyment** [comment]
What if we always allow to switch room but apply your reset code each time a room is switched
```
// Reset variables
rectx = recty = -1;
tmpLTcornerTileX = rectselectstartTileX = tmpLTcornerTileY = rectselectstartTileY = -1;
rectwidth = rectheight = 0;
has_a_rect = false;
dragInitmouseX = dragInitmouseY = -1;
rectdata.clear();
```

in void WL4EditorWindow::SetCurrentRoomId(int roomid)
(a method resetRect() can be created in MainGraphicsView.cpp and then called with ui->graphicsView->resetRect() for example)
